
nginx_remove_default_vhost: false
nginx_vhosts:
- listen: "80"
  server_name: "192.168.1.12"
  root: "/usr/share/nginx/html"
  index: "index.php index.html index.htm"
  error_page: "404 /404.html"
  template: "{{ nginx_vhost_template }}"
  filename: "example.com.conf"
  extra_parameters: |
    location ~ \.php$ {
      fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
    }


wp_db_name: wordpress
wp_db_user: username
wp_db_password: password



download_url: "http://wordpress.org/latest.tar.gz"
 

wpdirectory: "/usr/share/nginx/html"

php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_webserver_daemon: "ngnix"
php_enable_php_fpm: true
php_enablerepo: "remi-php70,epel"
php_fpm_listen: "/var/run/php-fpm/php-fpm.sock"
php_fpm_pool_user: "nginx"
php_fpm_pool_group: "nginx"
php_packages:
   - php-mysql
   - php-fpm
