- hosts: test
  vars_files:
  - vars/main.yml
  sudo: yes


  roles:
  - python2-install
  - geerlingguy.nginx
  - geerlingguy.mysql
  - geerlingguy.repo-remi
  - geerlingguy.repo-epel
  - geerlingguy.php
  - geerlingguy.php-mysql
  - wordpress
